inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - Gemfile
    - 'db/schema.rb'
    - 'db/migrate/*'
    - config.ru
    - Rakefile
    - config/boot.rb
    - config/environment.rb
    - config/environments/*
    - config/initializers/*
    - config/puma.rb
    - config/spring.rb
